create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null,
  mode text not null,
  price numeric default 0,
  borrow_price numeric default 0,
  deposit_amount numeric default 0,
  duration_days integer default 1,
  owner_id uuid,
  owner_name text,
  image_url text,
  image_urls jsonb default '[]'::jsonb,
  location text default 'Local pickup',
  availability jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  listing_id bigint references public.listings(id) on delete cascade,
  sender_id uuid references auth.users(id) on delete cascade,
  recipient_id uuid references auth.users(id) on delete cascade,
  sender_name text not null,
  content text not null,
  created_at timestamptz default now()
);

-- Add messaging columns when upgrading an existing project.
alter table public.messages add column if not exists sender_id uuid references auth.users(id) on delete cascade;
alter table public.messages add column if not exists recipient_id uuid references auth.users(id) on delete cascade;

create table if not exists public.interests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  listing_id bigint not null references public.listings(id) on delete cascade,
  created_at timestamptz default now(),
  unique (user_id, listing_id)
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  listing_id bigint not null references public.listings(id) on delete cascade,
  requester_id uuid not null references auth.users(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  note text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined', 'cancelled')),
  created_at timestamptz default now(),
  check (end_date >= start_date)
);

alter table public.listings enable row level security;
alter table public.messages enable row level security;
alter table public.interests enable row level security;
alter table public.reservations enable row level security;

-- RLS policies filter rows, but PostgreSQL grants are still required before
-- Supabase's anon/authenticated API roles can access these tables.
grant usage on schema public to anon, authenticated;
grant select on table public.listings to anon, authenticated;
grant insert on table public.listings to authenticated;
grant usage, select on sequence public.listings_id_seq to authenticated;
grant select, insert on table public.messages to authenticated;
grant usage, select on sequence public.messages_id_seq to authenticated;
grant select, insert, delete on table public.interests to authenticated;
grant usage, select on sequence public.interests_id_seq to authenticated;
grant select, insert on table public.reservations to authenticated;
grant usage, select on sequence public.reservations_id_seq to authenticated;

drop policy if exists "Allow public read access to listings" on public.listings;
drop policy if exists "Allow public insert access to listings" on public.listings;
drop policy if exists "Allow public read access to messages" on public.messages;
drop policy if exists "Allow public insert access to messages" on public.messages;
drop policy if exists "Users can read their messages" on public.messages;
drop policy if exists "Users can message listing owners" on public.messages;
drop policy if exists "Users can read their favorites" on public.interests;
drop policy if exists "Users can add favorites" on public.interests;
drop policy if exists "Users can remove favorites" on public.interests;
drop policy if exists "Reservation participants can read requests" on public.reservations;
drop policy if exists "Users can request reservations" on public.reservations;

drop policy if exists "public-read-buckets-listings" on storage.buckets;
drop policy if exists "public-read-objects-listings" on storage.objects;
drop policy if exists "public-upload-objects-listings" on storage.objects;
drop policy if exists "users-delete-own-listing-images" on storage.objects;

create policy "Allow public read access to listings" on public.listings for select using (true);
create policy "Allow public insert access to listings" on public.listings
  for insert to authenticated
  with check (
    owner_id = auth.uid()
    and char_length(btrim(title)) between 3 and 120
    and char_length(btrim(description)) between 10 and 5000
    and category in ('Tools & Hardware', 'Electronics', 'Vehicles', 'Home & Garden', 'Fashion & Style', 'Sporting Goods')
    and mode in ('Borrow only', 'Borrow + Buy', 'Buy only')
    and price between 0 and 1000000
    and borrow_price between 0 and 1000000
    and deposit_amount between 0 and 1000000
    and duration_days between 1 and 365
    and char_length(coalesce(owner_name, '')) <= 120
    and char_length(coalesce(location, '')) <= 160
    and jsonb_typeof(image_urls) = 'array'
    and jsonb_array_length(image_urls) <= 6
    and jsonb_typeof(availability) = 'array'
    and jsonb_array_length(availability) <= 366
  );
create policy "Users can read their messages" on public.messages
  for select to authenticated
  using (sender_id = auth.uid() or recipient_id = auth.uid());
create policy "Users can message listing owners" on public.messages
  for insert to authenticated
  with check (
    sender_id = auth.uid()
    and char_length(btrim(sender_name)) between 1 and 120
    and char_length(btrim(content)) between 1 and 2000
    and exists (
      select 1 from public.listings
      where public.listings.id = messages.listing_id
        and public.listings.owner_id = messages.recipient_id
        and messages.sender_id <> messages.recipient_id
    )
  );

create policy "Users can read their favorites" on public.interests
  for select to authenticated using (user_id = auth.uid());
create policy "Users can add favorites" on public.interests
  for insert to authenticated with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.listings
      where public.listings.id = interests.listing_id
        and public.listings.owner_id <> interests.user_id
    )
  );
create policy "Users can remove favorites" on public.interests
  for delete to authenticated using (user_id = auth.uid());

create policy "Reservation participants can read requests" on public.reservations
  for select to authenticated
  using (requester_id = auth.uid() or owner_id = auth.uid());
create policy "Users can request reservations" on public.reservations
  for insert to authenticated
  with check (
    requester_id = auth.uid()
    and requester_id <> owner_id
    and status = 'pending'
    and start_date >= current_date
    and end_date >= start_date
    and char_length(coalesce(note, '')) <= 1000
    and exists (
      select 1 from public.listings
      where public.listings.id = reservations.listing_id
        and public.listings.owner_id = reservations.owner_id
        and (reservations.end_date - reservations.start_date + 1) <= public.listings.duration_days
        and (
          jsonb_array_length(public.listings.availability) = 0
          or (
            public.listings.availability ? reservations.start_date::text
            and public.listings.availability ? reservations.end_date::text
          )
        )
    )
  );

create unique index if not exists reservations_one_pending_request
  on public.reservations (listing_id, requester_id, start_date, end_date)
  where status = 'pending';

-- Create the storage bucket if needed. ON CONFLICT keeps this script rerunnable.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'listings',
  'listings',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "public-read-buckets-listings" on storage.buckets
  for select
  using (id = 'listings');

create policy "public-read-objects-listings" on storage.objects
  for select
  using (bucket_id = 'listings');

create policy "public-upload-objects-listings" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'listings'
    and (storage.foldername(name))[1] = auth.uid()::text
    and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp', 'gif')
    and coalesce((metadata ->> 'size')::bigint, 0) <= 5242880
  );

create policy "users-delete-own-listing-images" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'listings'
    and owner_id = auth.uid()::text
    and (storage.foldername(name))[1] = auth.uid()::text
  );
